# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/akita/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),akita)

$(call add-radio-file-sha1-checked,radio/abl.img,fe757926d8c63dc295115feed4a8da2d1f9a0743)
$(call add-radio-file-sha1-checked,radio/bl1.img,1ebb352a7eca84683305f9654b850858daeaac88)
$(call add-radio-file-sha1-checked,radio/bl2.img,522373d4f8363ecba2799a26d2f57dd4949e75d4)
$(call add-radio-file-sha1-checked,radio/bl31.img,8ff94555903001df9a5cf017d10b09d99446eacc)
$(call add-radio-file-sha1-checked,radio/gcf.img,c62f2eac9c6b5ec8d28d4787165ddb128e47fac6)
$(call add-radio-file-sha1-checked,radio/gsa.img,8a70bee1d9236d9c35e7f04f8a9481181b999eda)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,8075d28cb5d1668c5a66cc032bf37d74f6ecffdf)
$(call add-radio-file-sha1-checked,radio/ldfw.img,dfbe5d5d6693516b43c01924fbf1bcc9e1cc8d25)
$(call add-radio-file-sha1-checked,radio/modem.img,755461cc47c49fcfb9153c7b892b7cc842539128)
$(call add-radio-file-sha1-checked,radio/pbl.img,4a870ff30de39a7cc700fc9204279e1f3dfe1557)
$(call add-radio-file-sha1-checked,radio/tzsw.img,a1fee3a8e1a4715dfe73cd21ce343b2c3e56b5a8)

endif
