# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/akita/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),akita)

$(call add-radio-file-sha1-checked,radio/abl.img,13277b0fbb2b8c8fccf81753a7a65caeff272cb4)
$(call add-radio-file-sha1-checked,radio/bl1.img,263276531b4f6f515ffc66aa87c2756ce6e3df8d)
$(call add-radio-file-sha1-checked,radio/bl2.img,472d900e3a99560cb9ba9d3d267326e0e13b8c1d)
$(call add-radio-file-sha1-checked,radio/bl31.img,643230df6fb0b486b449adce00b7c907dd4499f2)
$(call add-radio-file-sha1-checked,radio/gcf.img,b6bce8b81248b60685fc6b5b9064b12aa7d32d1c)
$(call add-radio-file-sha1-checked,radio/gsa.img,881c2a296a7baa89df450cfc89cf16f2c36a8294)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,fc981a5531af60362de82a37534019cf373a13a7)
$(call add-radio-file-sha1-checked,radio/ldfw.img,1c515b1db1598230d6bfa831cdd1cabd320e992c)
$(call add-radio-file-sha1-checked,radio/modem.img,6e42d98fdd9ca7444d011c52d480783f315239b2)
$(call add-radio-file-sha1-checked,radio/pbl.img,f158f0ebbdaa84ecca5b1cc894db4c0742107556)
$(call add-radio-file-sha1-checked,radio/tzsw.img,b6bd68fe5eff8f6cd9252dd65736caf9ac280ebf)

endif
