# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/akita/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),akita)

$(call add-radio-file-sha1-checked,radio/abl.img,0546b844ac0d153209e4b8360bde868fa5dbc912)
$(call add-radio-file-sha1-checked,radio/bl1.img,f84c1b071c15208a26e4cce7ce534efef016a4ca)
$(call add-radio-file-sha1-checked,radio/bl2.img,9b197abb497b9a898456e8a7171e9013bcb883d7)
$(call add-radio-file-sha1-checked,radio/bl31.img,0fd6d5de0132044ef76a67ea1ae30185381a2247)
$(call add-radio-file-sha1-checked,radio/gcf.img,1e1240d87f2c3e4278097b5f17215ff20df0688a)
$(call add-radio-file-sha1-checked,radio/gsa.img,4bc4fbd561a2807cca5609df5565a200975955f7)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,6fbe2a34f85cb616ff353b2cda9e2364db6fa8df)
$(call add-radio-file-sha1-checked,radio/ldfw.img,7633c77c69e6ffd8102e62fae194561770035d35)
$(call add-radio-file-sha1-checked,radio/modem.img,755461cc47c49fcfb9153c7b892b7cc842539128)
$(call add-radio-file-sha1-checked,radio/pbl.img,0ba18e30e8b8afeb65b9a9852ed2fd2a2aba8e14)
$(call add-radio-file-sha1-checked,radio/tzsw.img,ff959d92b2d363706e87ef68cb8d6f2c92821e50)

endif
